# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='photo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.TextField(blank=True),
        ),
    ]
