# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180608_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vidoe_length',
            new_name='video_length',
        ),
    ]
