# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180608_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='photo',
            field=models.ImageField(upload_to='videoPhotos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FileField(upload_to='videos'),
        ),
    ]
